var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/login/route.js")
R.c("server/chunks/[root-of-the-server]__0o.bin5._.js")
R.c("server/chunks/node_modules_zod_v3_external_0_2gmko.js")
R.c("server/chunks/_0mg2qq3._.js")
R.c("server/chunks/src_lib_supabase_ts_0kwbptk._.js")
R.c("server/chunks/[root-of-the-server]__0lik6q-._.js")
R.c("server/chunks/node_modules_next_04~_e52._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_login_route_actions_0o428.q.js")
R.m(7620)
module.exports=R.m(7620).exports
