// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[locale]" | "/[locale]/account/api-keys" | "/[locale]/account/referrals" | "/[locale]/api-docs" | "/[locale]/api-platform" | "/[locale]/best-claude-skill-for/[useCase]" | "/[locale]/blog" | "/[locale]/blog/[slug]" | "/[locale]/cart" | "/[locale]/free" | "/[locale]/free/download/[slug]" | "/[locale]/kits" | "/[locale]/kits/[slug]" | "/[locale]/library" | "/[locale]/privacy" | "/[locale]/pro" | "/[locale]/refunds" | "/[locale]/terms" | "/[locale]/thanks" | "/[locale]/vs/[competitor]" | "/[locale]/wizard" | "/admin"
type AppRouteHandlerRoutes = "/api/account/api-keys" | "/api/account/api-keys/[id]" | "/api/account/request-link" | "/api/admin/login" | "/api/admin/stats" | "/api/api-checkout" | "/api/checkout" | "/api/download/[slug]" | "/api/lead-magnet/claim" | "/api/lead-magnet/download/[slug]" | "/api/library/request" | "/api/newsletter/confirm" | "/api/newsletter/subscribe" | "/api/pro-checkout" | "/api/recommend" | "/api/v1/kits" | "/api/v1/kits/[idOrSlug]" | "/api/v1/kits/[idOrSlug]/download" | "/api/v1/recommend" | "/api/v1/usage" | "/api/webhook/stripe" | "/api/wishlist/list" | "/api/wishlist/save" | "/og/blog/[slug]" | "/og/kit/[slug]" | "/og/page"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/account/api-keys": { "locale": string; }
  "/[locale]/account/referrals": { "locale": string; }
  "/[locale]/api-docs": { "locale": string; }
  "/[locale]/api-platform": { "locale": string; }
  "/[locale]/best-claude-skill-for/[useCase]": { "locale": string; "useCase": string; }
  "/[locale]/blog": { "locale": string; }
  "/[locale]/blog/[slug]": { "locale": string; "slug": string; }
  "/[locale]/cart": { "locale": string; }
  "/[locale]/free": { "locale": string; }
  "/[locale]/free/download/[slug]": { "locale": string; "slug": string; }
  "/[locale]/kits": { "locale": string; }
  "/[locale]/kits/[slug]": { "locale": string; "slug": string; }
  "/[locale]/library": { "locale": string; }
  "/[locale]/privacy": { "locale": string; }
  "/[locale]/pro": { "locale": string; }
  "/[locale]/refunds": { "locale": string; }
  "/[locale]/terms": { "locale": string; }
  "/[locale]/thanks": { "locale": string; }
  "/[locale]/vs/[competitor]": { "locale": string; "competitor": string; }
  "/[locale]/wizard": { "locale": string; }
  "/admin": {}
  "/api/account/api-keys": {}
  "/api/account/api-keys/[id]": { "id": string; }
  "/api/account/request-link": {}
  "/api/admin/login": {}
  "/api/admin/stats": {}
  "/api/api-checkout": {}
  "/api/checkout": {}
  "/api/download/[slug]": { "slug": string; }
  "/api/lead-magnet/claim": {}
  "/api/lead-magnet/download/[slug]": { "slug": string; }
  "/api/library/request": {}
  "/api/newsletter/confirm": {}
  "/api/newsletter/subscribe": {}
  "/api/pro-checkout": {}
  "/api/recommend": {}
  "/api/v1/kits": {}
  "/api/v1/kits/[idOrSlug]": { "idOrSlug": string; }
  "/api/v1/kits/[idOrSlug]/download": { "idOrSlug": string; }
  "/api/v1/recommend": {}
  "/api/v1/usage": {}
  "/api/webhook/stripe": {}
  "/api/wishlist/list": {}
  "/api/wishlist/save": {}
  "/og/blog/[slug]": { "slug": string; }
  "/og/kit/[slug]": { "slug": string; }
  "/og/page": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
