// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/[locale]/account/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/api-keys">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/account/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/account/referrals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/referrals">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/account/referrals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api-docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/api-docs">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api-docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/api-platform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/api-platform">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/api-platform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/best-claude-skill-for/[useCase]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/best-claude-skill-for/[useCase]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/best-claude-skill-for/[useCase]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/cart">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/free/download/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/free/download/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/free/download/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/free/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/free">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/free/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/kits/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/kits/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/kits/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/kits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/kits">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/kits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/library">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/pro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/pro">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/pro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/refunds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/refunds">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/refunds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/terms">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/thanks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/thanks">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/thanks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/vs/[competitor]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/vs/[competitor]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/vs/[competitor]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/wizard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/wizard">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/wizard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/api-keys/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/api-keys/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/api-keys/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/api-keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/api-keys">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/api-keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/request-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/request-link">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/request-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/api-checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/api-checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/api-checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/download/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/download/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/download/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lead-magnet/claim/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lead-magnet/claim">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lead-magnet/claim/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lead-magnet/download/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lead-magnet/download/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lead-magnet/download/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/library/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/library/request">> = Specific
  const handler = {} as typeof import("../../../src/app/api/library/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/newsletter/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/newsletter/confirm">> = Specific
  const handler = {} as typeof import("../../../src/app/api/newsletter/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/newsletter/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/newsletter/subscribe">> = Specific
  const handler = {} as typeof import("../../../src/app/api/newsletter/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/pro-checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pro-checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/pro-checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/recommend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recommend">> = Specific
  const handler = {} as typeof import("../../../src/app/api/recommend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/kits/[idOrSlug]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/kits/[idOrSlug]/download">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/kits/[idOrSlug]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/kits/[idOrSlug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/kits/[idOrSlug]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/kits/[idOrSlug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/kits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/kits">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/kits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/recommend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/recommend">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/recommend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/usage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/usage">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/usage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/webhook/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhook/stripe">> = Specific
  const handler = {} as typeof import("../../../src/app/api/webhook/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/wishlist/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wishlist/list">> = Specific
  const handler = {} as typeof import("../../../src/app/api/wishlist/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/wishlist/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wishlist/save">> = Specific
  const handler = {} as typeof import("../../../src/app/api/wishlist/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/og/blog/[slug]/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/og/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/og/blog/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/og/kit/[slug]/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/og/kit/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/og/kit/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/og/page/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/og/page">> = Specific
  const handler = {} as typeof import("../../../src/app/og/page/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
